### ISSUE TITLE
USD currency code instead of EUR 

### ISSUE THREAD

**Issue by Penguinjanator** [Tanibox/tania-core#103]
The only specific changes made to the src code were done to all instances of &euro; to &dollar; 
so that forms would display $. This change works fine.
The problem is after submission the SQL database still shows EUR.
so i made a change to resources/js/stores/stubs/inventory.js
`currency_code: 'EUR',`
to 
`currency_code: 'USD',`
this change throws this error when attempting to submit forms with currencyCode.

` error_message="Wrong currency code" field_name= file=farm_server.go line=1438 request_id=OMvy4MoydbzAYzJs4v4zcTqPdqBOztqu user_uid="<nil>"`

`form_values="map[chemical_type:[] currency_code:[USD] expiration_date:[2020-04-15] farm_id:[] is_expense:[] name:[3242] notes:[] plant_type:[VEGETABLE] price_per_unit:[2] produced_by:[42] quantity:[42] quantity_unit:[SEEDS] type:[seed] uid:[]]" host="localhost:8080" ip=127.0.0.1 method=POST query_string= request_id=OMvy4MoydbzAYzJs4v4zcTqPdqBOztqu roundtrip=16628 roundtrip_human=16.6286ms status=500 uri=/api/farms/inventories/materials/seed user_agent="Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"`

**Comment by Penguinjanator** [comment]
also using v1.6 of Tania because 1.7 and up did not build on windows for me.

**Comment by bepitulaz** [comment]
Hi @Penguinjanator,

Do you still have the issue with this one?
