### ISSUE TITLE
paths to db in conf.json

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#12]
i installed a newer version of golang via a PPA which broke `go get` in several ways, so i cloned the project manually, ran `npm install` successfully after editing the `conf.json` file (which by the way needs to replace the tania-server references with tania-core) but when i try to run `go run main.go` i get this error:

<pre>
2018/04/13 08:14:02 Using 'conf.json' configuration
2018/04/13 08:14:02 Using sqlite persistance engine
2018/04/13 08:14:02 Creating database file /home/me/go/src/github.com/Tanibox/tania-server/db/sqlite/tania.db
2018/04/13 08:14:02 Using SQLite at /home/me/go/src/github.com/Tanibox/tania-server/db/sqlite/tania.db
2018/04/13 08:14:02 Executing DDL file for /home/me/go/src/github.com/Tanibox/tania-server/db/sqlite/tania.db
panic: unable to open database file

goroutine 1 [running]:
main.initSqlite(0xc4201fe230)
	/home/me/.local/share/Trash/files/tania-core.3/main.go:365 +0x368
main.main()
	/home/me/.local/share/Trash/files/tania-core.3/main.go:49 +0xd0b
</pre>

but i had started from a fresh install and had edited the `conf.json` to replace tania-server with tania-core, where is it getting this path to tania-server?

**Comment by adhatama** [comment]
@bobombolo From what we can saw in your log, your path in your `conf.json` still refers to `.../Tanibox/tania-server/...` instead of `tania-core`. 
Then the `unable to open database file` error message indicates that you have a problem in your sqlite file. It could be missing because of wrong path or permission problem.

**Comment by bobombolo** [comment]
but this is my conf file:
<pre>
{
    "tania_persistence_engine": "sqlite",
    "demo_mode": true,
    "upload_path_area": "/home/me/go/src/github.com/Tanibox/tania-core/uploads/areas",
    "upload_path_crop": "/home/me/go/src/github.com/Tanibox/tania-core/uploads/crops",
    "sqlite_path": "/home/me/go/src/github.com/Tanibox/tania-core/db/sqlite/tania.db",
    "mysql_host": "127.0.0.1",
    "mysql_port": "3306",
    "mysql_dbname": "tania",
    "mysql_user": "root",
    "mysql_password": "root",
    "redirect_uri": "http://localhost:8080/",
    "client_id": "f0ece679-3f53-463e-b624-73e83049d6ac"
}
</pre>
