### ISSUE TITLE
http server started but in the browser there is an error "message	"Not Found""

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#13]
![screenshot from 2018-04-13 15-49-34](https://user-images.githubusercontent.com/25610408/38755082-6aa9f64e-3f32-11e8-89cb-3dfd1aec324f.png)

**Comment by bobombolo** [comment]
looks like there is an error when requesting the "/" uri as well as favicon.ico

<pre>
~/go/src/github.com/Tanibox/tania-core $ go run main.go
2018/04/13 15:44:25 Using 'conf.json' configuration
2018/04/13 15:44:25 Using sqlite persistance engine
2018/04/13 15:44:25 Creating database file /home/danjor/go/src/github.com/Tanibox/tania-core/db/sqlite/tania.db
2018/04/13 15:44:25 Using SQLite at /home/danjor/go/src/github.com/Tanibox/tania-core/db/sqlite/tania.db
2018/04/13 15:44:25 Executing DDL file for /home/danjor/go/src/github.com/Tanibox/tania-core/db/sqlite/tania.db
2018/04/13 15:44:25 DDL file executed
2018/04/13 15:44:25 User created with default username and password

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.dev
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8080
{"time":"2018-04-13T15:45:15.294772096-04:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"340","message":"code=404, message=Not Found"}
{"time":"2018-04-13T15:45:15.29483712-04:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/","status":404, "latency":128021,"latency_human":"128.021µs","bytes_in":0,"bytes_out":23}
{"time":"2018-04-13T15:45:15.507110069-04:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"340","message":"code=404, message=Not Found"}
{"time":"2018-04-13T15:45:15.507194705-04:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/favicon.ico","status":404, "latency":152598,"latency_human":"152.598µs","bytes_in":0,"bytes_out":23}
{"time":"2018-04-13T15:45:15.544015422-04:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"340","message":"code=404, message=Not Found"}
{"time":"2018-04-13T15:45:15.544072303-04:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/favicon.ico","status":404, "latency":100695,"latency_human":"100.695µs","bytes_in":0,"bytes_out":23}
</pre>

**Comment by bepitulaz** [comment]
Hello @bobombolo. I've made a new release with pre-built binaries for Linux and Windows. You can try it https://github.com/Tanibox/tania-core/releases/tag/1.5.1 and let us know whether it's work for you or not.

**Comment by bobombolo** [comment]
yes that works! thanks.
