### ISSUE TITLE
instructions, how to add livestock, employees, etc

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#14]
In the menu I only have options to add Materials, Tasks and in Production I can only add Areas, Crops and Reservoirs. Also where could I edit the farm properties such as longitude/latitude after creating the farm? Also why does an Area have to be associated with a Reservoir (we do not irrigate our fields)?

here is a screenshot of what I see:

![screenshot from 2018-04-14 10-49-11](https://user-images.githubusercontent.com/25610408/38769490-040cb5ac-3fd2-11e8-8e47-113c1e4047ee.png)

**Comment by bobombolo** [comment]
Also what are the consequences of the Farm Type? If I say "Livestock" then am I going to be limited to certain functions? Also where can I add a new farm? I see the option to "switch farm" but not one to create farm.

**Comment by fkornel** [comment]
I'm also interested.

**Comment by prasmalla** [comment]
you can add a new farm here http://localhost:8080/#/intro/farm
+1 for documentation and i can help with that

**Comment by bepitulaz** [comment]
@prasmalla woah, it will be helpful. I think you can create a directory and put the documentation in markdown format, then PR it.

**Comment by bepitulaz** [comment]
Hi everyone, you can see the documentation on our new website http://usetania.org/docs/

Thanks to @yuulye who remind me about this issue. Now, I close this issue.
