### ISSUE TITLE
Can't log in with default username & password

### ISSUE THREAD

**Issue by ech0r** [Tanibox/tania-core#15]
Hello, I've followed the installation steps exactly. 

When I try the default user/pass of tania/tania, I cannot log in.

I've checked the database file, tania.db and it shows the default user account is in there. 
It seems for some reason the login page is unable to read that file?

Any help would be much appreciated.

My conf.json looks like this:

    "tania_persistence_engine": "sqlite",
    "demo_mode": true,
    "upload_path_area": "uploads/areas",
    "upload_path_crop": "uploads/crops",
    "sqlite_path": "db/sqlite/tania.db",
    "mysql_host": "127.0.0.1",
    "mysql_port": "3306",
    "mysql_dbname": "tania",
    "mysql_user": "root",
    "mysql_password": "root",
    "redirect_uri": "http://localhost:8080/",
    "client_id": "f0ece679-3f53-463e-b624-73e83049d6ac"

**Comment by adhatama** [comment]
@ech0r Did you use custom Go port instead of the default `:8080`?

**Comment by ech0r** [comment]
I was using port 8080, is there another port I should be using?

Thanks for replying :)

**Comment by adhatama** [comment]
@ech0r No. It should be good.
And did you use `localhost` for the hostname too?
If yes, then I don't have a clue why it didn't work on your machine.
Can you please give us a log from the browser console and the response when calling `http://yourhostname:8080/api/authorize`?
If you are not using `localhost` for your hostname, you need to change your `conf.json` in `"redirect_uri": "http://localhost:8080/"` to match your current hostname.

**Comment by ech0r** [comment]
I get the following response when visiting http://localhost:8080/api/authorize

{"message":"Method Not Allowed"}

**Comment by adhatama** [comment]
@ech0r Sorry, I mean that can you check out from your browser network what is the response of http://localhost:8080/api/authorize when you're doing login?
When doing login, the frontend will request to http://localhost:8080/api/authorize so we could know what actually happened when login by looking at the response from that request.

**Comment by ech0r** [comment]
When I try to login I see a POST request to http://localhost/api/authorize

Then below that I get OPTIONS with http://localhost:8080/?access_token=63592b30-498d-4b60-b563-561d5bc33ff1&state=random-string&expires_in=0

I'm running Tania inside of a Docker container with port 80 mapped to 8080 on the tania container. 

So to access the web app I just go to http://localhost

![image](https://user-images.githubusercontent.com/18295572/39165561-e08b76bc-4739-11e8-894d-27549ab30d6c.png)

**Comment by adhatama** [comment]
@ech0r Thanks for the report. 
Can you please change your `"redirect_uri": "http://localhost:8080/"` to `"redirect_uri": "http://localhost/"` in your `conf.json`? Because your web apps is using `localhost` without port so after login, then it will be redirected to that redirect url.

**Comment by bepitulaz** [comment]
I think this issue had been solved.
