### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by andrewlytvyn** [Tanibox/tania-core#16]
can i translate or add some ui language?)
my language is Ukrain

**Comment by bepitulaz** [comment]
Of course, you can. Thank you :)

**Comment by andrewlytvyn** [comment]
vue-i18n?

**Comment by fkornel** [comment]
I'm also interested in doing localization to Hungarian.
There will be new commits to tania-core or it is EOL already?

**Comment by bepitulaz** [comment]
There will be a new commit. This version is maintained, but since we are
still a small team (3 developers) and have other commercial projects, so
the update need a long time.

We will share the roadmap for this oss version very soon.

**Comment by fkornel** [comment]
Thanks @bepitulaz for the prompt response!
