### ISSUE TITLE
(cosmetic) default paths for areas and crops in "taniad -h"

### ISSUE THREAD

**Issue by pimar57** [Tanibox/tania-core#205]
Hello folks, 

I've see in help message of taniad, the default upload paths are with values which doest not match conf.json & all. 

I think it should be:

> --upload_path_area string           Upload path for the Area photo (default "**uploads**/area**s**")
>  --upload_path_crop string           Upload path for the Crop photo (default "**uploads**/crop**s**")

I found them in backend/config/config.go but don't know how to submit a patch.

Continue this great initiative !
Pierre

**Comment by bepitulaz** [comment]
Hey, thanks @pimar57. We'll check it.

**Comment by pimar57** [comment]
Hi, Nice!

**Comment by pablojimpas** [comment]
Thanks for the catch @pimar57! Now it's fixed in the 2.0 dev branch.
