### ISSUE TITLE
Cannot add tasks

### ISSUE THREAD

**Issue by prasmalla** [Tanibox/tania-core#21]
hi, im using mysql for db and the app crashes when adding task

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ec96a]

goroutine 849 [running]:
github.com/Tanibox/tania-core/src/tasks/repository/mysql.(*TaskReadRepositoryMysql).Save.func1(0xc4201340c0, 0xc42000e770, 0xc420076480)
        /root/go/src/github.com/Tanibox/tania-core/src/tasks/repository/mysql/task_read_repository.go:44 +0x10a
created by github.com/Tanibox/tania-core/src/tasks/repository/mysql.(*TaskReadRepositoryMysql).Save
        /root/go/src/github.com/Tanibox/tania-core/src/tasks/repository/mysql/task_read_repository.go:22 +0x71
exit status 2

**Comment by adhatama** [comment]
@prasmalla Thanks for the report.
This is confirmed bug. We are working on it.

**Comment by lynxluna** [comment]
@adhatama is the bug is confirmed as fixed. If so, please close this issue.
