### ISSUE TITLE
cannot login with mobile devices

### ISSUE THREAD

**Issue by prasmalla** [Tanibox/tania-core#23]
hi, using default username/password says incorrect login on mobile devices (ipad / android) works on iphone

INFO[0034] Response Info                                 host="aquaponicsnepal.com:4200" ip=207.237.24.213 method=POST request_id=ziFszEuojQibFgtol63kHd0pFLpmBDjA roundtrip=70129 roundtrip_human=70.129847ms status=302 uri=/api/authorize user_agent="Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1"
INFO[0034] Response Info                                 host="aquaponicsnepal.com:4200" ip=207.237.24.213 method=GET request_id=F8WVGfyaOlWS0hUQKwNw6ydmjYPYBv9L roundtrip=86 roundtrip_human="86.606µs" status=200 uri="/?access_token=35f3698f-f0ad-4e6e-a003-5b69e6ed563c&state=random-string&expires_in=0" user_agent="Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1"

**Comment by adhatama** [comment]
@prasmalla Have you checked your `redirect_uri` in your `conf.json` for `aquaponicsnepal.com:4200`?
For example, if you had multiple host, then you need to add all of them:
```
   "redirect_uri": [
        "http://localhost:8080",
        "http://localhost:9090",
        "http://127.0.0.1:8080",
        "http://192.168.0.3:8080"
```

Please update to the latest commits from branch `master` for the multiple `redirect_uri` supports

**Comment by lynxluna** [comment]
Does this fix your problem @prasmalla ?

**Comment by prasmalla** [comment]
@adhatama i have a single host for redirect_uri
@lynxluna phones work ok. guess it is just an ipad issue

**Comment by lynxluna** [comment]
I'll close this issue then.
