### ISSUE TITLE
Create Farm Country Select Bug

### ISSUE THREAD

**Issue by chrigui** [Tanibox/tania-core#24]
Country list Empty only when adding a 2nd Farm.
<img width="957" alt="screen shot 2018-08-12 at 22 14 59" src="https://user-images.githubusercontent.com/1286895/44005515-57724ca2-9e7d-11e8-8a8b-ba96472e1269.png">

**Comment by adhatama** [comment]
@chrigui How did you create the second farm? Because we don't have a feature to create the second farm for now.

**Comment by chrigui** [comment]
@adhatama i followed issue #14 /farms/cretate i though the feature is there :)

thank you.
