### ISSUE TITLE
[Upgrading Issue] Can someone help me to look the error in Webpack?

### ISSUE THREAD

**Issue by bepitulaz** [Tanibox/tania-core#33]
Before adding more features for the next version, I update all JS dependencies. I upgraded Babel 7, Vue 2, and Webpack 4. But, I don't understand why Webpack always fails to build the source code. Can someone help me? This is my PR https://github.com/Tanibox/tania-core/pull/32

I'm not good at doing front-end.

**Comment by resir014** [comment]
After a couple hours of wrestling with Laravel Mix, I think I got it to work.

Still need to test locally though, I'm not good at backend stuff, so I don't know how to get Golang to work locally 😅 

![image](https://user-images.githubusercontent.com/5663877/51488550-69ff6f00-1dd8-11e9-9c60-a2aaf9154eb9.png)

**Comment by resir014** [comment]
One minor issue that I still have is this double-slash in the injected HTML. Still investigating.

<img width="818" alt="screen shot 2019-01-22 at 00 03 03" src="https://user-images.githubusercontent.com/5663877/51488955-8059fa80-1dd9-11e9-8029-b0e216b2f921.png">

**Comment by bepitulaz** [comment]
Thank you, @resir014. I will test your works on my laptop. Hopefully, it can be built now.

**Comment by resir014** [comment]
Slowly getting there...

Now I'm having issues loading dynamic components. Right now I'm trying to tear away the loaders and re-including them one by one. Hopefully it'll work.

![image](https://user-images.githubusercontent.com/5663877/51511341-7fee4d80-1e33-11e9-80f8-679f63dfbf00.png)

**Comment by bepitulaz** [comment]
@resir014 I've tested locally. It compiled successfully, but I notice there's still an error related to `pug-loader`.

![image](https://user-images.githubusercontent.com/313962/51512217-e24d4b00-1e3f-11e9-94cc-3e25cde56369.png)

You can reproduce it by running `yarn run unit` or `npm run unit`. The template is also not rendered on the browser.

![image](https://user-images.githubusercontent.com/313962/51512254-132d8000-1e40-11e9-8c5d-a8e08bfd657f.png)

**Comment by bepitulaz** [comment]
I'm fetching your update. How to reproduce the package import issue?

**Comment by bepitulaz** [comment]
Ok, I got that error too. `yarn run unit` and `yarn run dev` is successfully executed.

**Comment by resir014** [comment]
@bepitulaz Yeah, that's what I'm still struggling with.

I just got home so I could only respond to your message now, but all I did was running `yarn unit`, `yarn dev`, then testing it inside the Go app with `go build` and running the compiled binary.

**Comment by bepitulaz** [comment]
@resir014, since our main issue to upgrade dependencies, is solved. I think better if I disable the Vue lazy load for this moment. Because we also want to modify and add some features to the Vue template itself.

It works after I disable it. I will merge your PR ;)

![image](https://user-images.githubusercontent.com/313962/51650977-36ce0300-1fc5-11e9-9ed0-909c4bb7226b.png)

**Comment by resir014** [comment]
@bepitulaz Awesome. Thanks for your help!

**Comment by bepitulaz** [comment]
@resir014 Big thanks for you! Awesome works!
