### ISSUE TITLE
installation, repo for tania-server missing?

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#4]
when I run 
`go get github.com/Tanibox/tania-server`

I get this:

`#cd .; git clone https://github.com/Tanibox/tania-server /home/me/go/src/github.com/Tanibox/tania-server`
`Cloning into '/home/me/go/src/github.com/Tanibox/tania-server'...`
`remote: Repository not found.`
`fatal: repository 'https://github.com/Tanibox/tania-server/' not found`
`package github.com/Tanibox/tania-server: exit status 128`

**Comment by lynxluna** [comment]
I've sent PR #5. I hope @adhatama will be able to review and merge soon.

**Comment by adhatama** [comment]
@lynxluna Thank you for the PR

@bobombolo The PR https://github.com/Tanibox/tania-core/pull/5 has fixed your issue. Please pull the latest commit from `master` branch

**Comment by bobombolo** [comment]
well i am just following the install instructions:
"Clone the repo using go get github.com/Tanibox/tania-server"
so that should now say 
"Clone the repo using go get github.com/Tanibox/tania-core" right?

**Comment by lynxluna** [comment]
@adhatama yeah we need to find and search for `tania-server` string. 
@bobombolo yes that's should be the case.

**Comment by adhatama** [comment]
@bobombolo After `go get github.com/Tanibox/tania-core`, it should have `tania-core` folder in your `$GOPATH/src/github.com/Tanibox` 
Can you make sure of it?

**Comment by bobombolo** [comment]
yes it's there

**Comment by bobombolo** [comment]
i deleted that and ran it again, no errors this time related to tania-server, 

however there was this warning:

`package context: unrecognized import path "context" (import path does not begin with hostname)`

thanks

**Comment by bobombolo** [comment]
probably good to change the readme's installation instructions to reflect this
