### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by sturza** [Tanibox/tania-core#42]

**Comment by bepitulaz** [comment]
Hi @sturza, I am preparing a new way for the demo. I'm making a pre-built binary so that user can easily run it on their laptop/pc/server.

**Comment by sturza** [comment]
what about for people on your website?

**Comment by bepitulaz** [comment]
The demo website? No worries, the data there is always constantly reset. It's just a demo. We don't provide a SaaS solution yet.

**Comment by sturza** [comment]
no, i mean it does not work. it shows a white page and some errors in the console

**Comment by bepitulaz** [comment]
This website https://demo-tania.tanibox.com? Yes, I put the service off because I will provide the pre-built binaries for Windows, Linux, and MacOS. I'll update the readme soon.

**Comment by sturza** [comment]
got it. thanks
