### ISSUE TITLE
The short survey to improve Tania

### ISSUE THREAD

**Issue by bepitulaz** [Tanibox/tania-core#65]
Hi, GitHub community,

We are constantly improving Tania, the farm management software. We would like to hear from you the software developer and the farmer (some software developers are farmers too.) We invite you to participate in this short survey to help us create the best software to help farmers manage their farm business better. https://forms.gle/ShDVZm9FijMiM5KMA

Thank you,
Tanibox team

**Comment by prasmalla** [comment]
to further answer the platform question in the survey, i think it should be for all platforms) using [electron](https://github.com/electron/electron)

**Comment by bepitulaz** [comment]
Hi @prasmalla,

I don't have any experience with Golang and Electron. What I only know is we can write a desktop app with Electron in JS. Absolutely, Vue.js can be wrapped into an Electron app, but what about the Golang server?
