### ISSUE TITLE
Missing tab styling on Crop Detail

### ISSUE THREAD

**Issue by showcheap** [Tanibox/tania-core#70]
I think this page is missing styling on tab navigation, 
![Screenshot from 2019-07-16 19-37-03](https://user-images.githubusercontent.com/1310895/61294937-20309800-a801-11e9-93e9-dfc06310ed54.png)
Also after **Tegalan** text, it's contain dot (default html `<li>` style)

Expected style to be like this
![Screenshot from 2019-07-16 19-39-16](https://user-images.githubusercontent.com/1310895/61295068-743b7c80-a801-11e9-9ff9-a96c0267e839.png)

### Additional Info
I'm running tania from github repo, build it my self.
OS: Linux / Fedora 30
Browser: Firefox 68

**Comment by bepitulaz** [comment]
Yes, you are right. It supposed to be like in the Crops page. Can you try to fix it?
