### ISSUE TITLE
Can't build from source: cannot find package "github.com/labstack/echo/v4"

### ISSUE THREAD

**Issue by grojas7** [Tanibox/tania-core#74]
Hi, I'm trying to build Tania from source using the build instructions on the README.md but after typing ``go get`` I get the following error:

```
package github.com/labstack/echo/v4: cannot find package "github.com/labstack/echo/v4" in any of:
	/usr/lib/go-1.10/src/github.com/labstack/echo/v4 (from $GOROOT)
	/home/grojas/go/src/github.com/labstack/echo/v4 (from $GOPATH)
package github.com/labstack/echo/v4/middleware: cannot find package "github.com/labstack/echo/v4/middleware" in any of:
	/usr/lib/go-1.10/src/github.com/labstack/echo/v4/middleware (from $GOROOT)
	/home/grojas/go/src/github.com/labstack/echo/v4/middleware (from $GOPATH)
```

**Machine**
``Linux chbk-gllm-6p 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux``
**Go Version**
``go version go1.10.4 linux/amd64``

**Comment by bepitulaz** [comment]
Hello @grojas7. Tania is using Go module. It's the official way for dependency management in the latest Go version. So, you can upgrade your Go from 1.10 to 1.12. Go module was supported since 1.11. Thanks.

**Comment by grojas7** [comment]
**It worked!** Thanks for the help. (Didn't double check the requirements against my setup, my bad)
