### ISSUE TITLE
PDOException:

### ISSUE THREAD

**Issue by boilermanc** [Tanibox/tania-core#76]
So close...

Took a good while to get the environment setup and running but go there! But now I am having a connection issue I cannot resolve. 

this worked fine:

`root@localhost:/var/www/vhosts/sweetwaterurbanfarms.com/farm.sweetwaterurbanfarms.com# ./tania-core
INFO[0000] Using config file at /var/www/vhosts/sweetwaterurbanfarms.com/farm.sweetwaterurbanfarms.com/conf.json
INFO[0000] Using mysql persistance engine
INFO[0000] Using MySQL at localhost:3306/tania
INFO[0000] DDL file executed
INFO[0000] User created with default username and password
`

but then I get this error when I try to launch the site:

`PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in lock_may_be_available() (line 167 of /homepages/30/d692292546/htdocs/sweetwaterfarm/includes/lock.inc).`

thanks!

**Comment by bepitulaz** [comment]
I'm not sure about this issue because we don't use PHP.
