### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by boilermanc** [Tanibox/tania-core#77]
Decided to try to build again. Server started just fine.

root@localhost:/var/www/vhosts/sweetwaterurbanfarms.com/farm.sweetwaterurbanfarms.com# ./tania-core
INFO[0000] Using config file at /var/www/vhosts/sweetwaterurbanfarms.com/farm.sweetwaterurbanfarms.com/conf.json
INFO[0000] Using mysql persistance engine
INFO[0000] Using MySQL at 127.0.0.1:3306/tania
INFO[0000] DDL file executed
INFO[0000] User tania has already created

Now I get a 403 error on the server. I cleared browser cache etc.

**Comment by bepitulaz** [comment]
May I see your `config.json`?
