### ISSUE TITLE
GLIBC_2.28' not found 

### ISSUE THREAD

**Issue by boilermanc** [Tanibox/tania-core#78]
Trying run the build for tania-v1.7-linux. When I do, I get the following error. As far as I can tell that is not something that is easy to fix on a system. I have tried the update commands but they do not update my version.

`./tania-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./tania-core)`

**Comment by bepitulaz** [comment]
If you are in any Debian distros, try to install it with `apt-get install build-essential`. It seems your OS doesn't have the `libc` installed.
