### ISSUE TITLE
Raspian Install issue

### ISSUE THREAD

**Issue by boilermanc** [Tanibox/tania-core#90]
Trying to install on raspian. I downloaded and untared the linux build. This is the error:

`pi@raspberrypi:/var/www $ ./tania-core
-bash: ./tania-core: cannot execute binary file: Exec format error
pi@raspberrypi:/var/www $ sudo ./tania-core
./tania-core: 1: ./tania-core:ELF: not found
./tania-core: 5: ./tania-core: Syntax error: word unexpected (expecting ")")

`

Thanks!

**Comment by bepitulaz** [comment]
The Linux pre-built binary is for amd64/x86 processor. Raspberry is using an ARM processor.

I can add the binary for Raspberry later next week. Meanwhile, if you don't want to wait, you can download the source code to your Raspberry, and build directly inside it.

**Comment by boilermanc** [comment]
Hi Asep! A build for the pi would be awesome. Let me know when it is up and i will give it a go!

thanks!

**Comment by bepitulaz** [comment]
@boilermanc hi, you can download the ARM version here https://drive.google.com/open?id=1813snCSe2x8vrOL9vnd1Jg7WeTal0w29

**Comment by boilermanc** [comment]
That's awesome! I am traveling this week but will test it next week!

⁣Sent from BlueMail ​

**Comment by quintinmutton** [comment]
Hi

Tried the ARM version and it runs but the password 'tania' doesn't work.  Can you let me know what the password is and/or create a updated version for 1.7.2?

Thanks
